#cloud-config
hostname: oc-web-a

fqdn: oc-web-a.vcf.sddc.lab

write_files:
- path: /etc/netplan/50-cloud-init.yaml
  content: |
    network:
     version: 2
     ethernets:
      ens192:
       addresses: [10.1.1.18/24]
       gateway4: 10.0.0.1
       dhcp6: false
       nameservers:
         addresses:
           - 10.0.0.221
         search:
           - vcf.sddc.lab
       dhcp4: false
       optional: true
- path: /etc/sysctl.d/60-disable-ipv6.conf
  owner: root
  content: |
    net.ipv6.conf.all.disable_ipv6=1
    net.ipv6.conf.default.disable_ipv6=1
    net.ipv6.conf.lo.disable_ipv6=1

- path: /root/disable_ipv6.sh
  permissions: 0744
  owner: root
  content: |
    #!/usr/bin/env bash
    set -e
    echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
    echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
- path: /etc/hosts
  content: 127.0.0.1 ubuntu
  append: true
runcmd:
- bash /root/disable_ipv6.sh
- netplan --debug apply
- sysctl -w net.ipv6.conf.all.disable_ipv6=1
- sysctl -w net.ipv6.conf.default.disable_ipv6=1
- sysctl -w net.ipv6.conf.lo.disable_ipv6=1
- apt-get -y update
- apt-get -y upgrade
- apt-get -y clean
- export USER="sam"
- export PASS="VMware123!"
- echo $USER:$PASS | /usr/sbin/chpasswd
- sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
- apt-get -y autoremove --purge
- apt-get -y install open-vm-tools
- apt-get -y install openssh-server
- apt-get -y install fzf
- systemctl enable ssh
- systemctl start ssh
- echo 'Cloud-init is done!' >> /tmp/finished.txt
packages:
  - php
  - php-cli
  - php-common
  - php-intl
  - php-gd
  - php-mbstring
  - php-xml
  - php-zip
  - php-curl
  - php-xmlrpc
  - unzip
  - open-vm-tools
timezone: America/Chicago
system_info:
  default_user:
    name: sam
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
disable_root: false
ssh_pwauth: yes  

users:
  - default
  - name: sam
    gecos: Tanzu User
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    password: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0
chpasswd:
  list: |
    sam: $6$rounds=4096$L2g1RTFocPEW$u.VUUpZKxik.Mr8l4XrZRAC5o0xiiNiWBy9gx.Vy5IkQxeIMAvzCbk2kU6yRHJhzMvdMSJ/VaStqoupJqkBfS0 
  expire: false
package_upgrade: true
package_reboot_if_required: true
power_state:
  delay: now
  mode: reboot
  message: Rebooting the OS
  condition: if [ -e /var/run/reboot-required ]; then exit 0; else exit 1; fi

